version: '3'
services:
  mongoapp:
    build: .
    image: tigrlily/mongo-app
    environment:
      NODE_ENV: development
      FOO: bar
      MONGO_URI: "mongodb://mongodb:27017"
    ports:
    - 3333:3333
    links:
      - mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    expose:
      - 27017